### PR TITLE
Create lt.js

### PR DESCRIPTION
**Pull request by tomux555**
Added website Lithuanian translation.

### CODE REVIEW

**Comment by RaMMicHaeL** [comment]
Thanks for the translation!

**Comment by RaMMicHaeL** [comment]
The unchecky.com website was updated.
I have also translated a missing string, based on Google Translate, I hope that it's correct.
https://github.com/unchecky/unchecky-translate/commit/3c753767c9d887fd85acbbb4d85961003f2831a1

**Comment by tomux555** [comment]
Actually it wasn't missing because in lithuanian the nouns are declensioned and conjunctions aren't needed. I can suggest e.g. Mike Williams (PC Advisor).

**Comment by RaMMicHaeL** [comment]
I would prefer to avoid having a special case for a single language.
How about e.g. Mike Williams - PC Advisor?

**Comment by tomux555** [comment]
It would be perfect. I observed some mine misspell: line 12 it should be the word "Pakeitimų", instead of "Paketimų" - misspell "i"; line 41 should be "variklį", instead of "varilį" - misspell "k"; line 121 "pašalinta" instead of "pašalinti". All the rest seems to be OK.

**Comment by RaMMicHaeL** [comment]
Fixed: https://github.com/unchecky/unchecky-translate/commit/0a446627cd7118b50f74663e826277da6631e4dd
unchecky.com was updated, too.
Thanks!

**Pull request merged**
