### PR TITLE
Updating app.txt (German) > Please do not pull, use #233 instead.

### PR DESCRIPTION
**Pull request by versat**
Translating new texts. Fixing errors in some translated texts and enhancing some texts so they sound better in german.

### CODE REVIEW

**Comment by RaMMicHaeL** [comment]
Thank you. While at it, can you please translate the untranslated texts in the [other files](https://github.com/unchecky/unchecky-translate/tree/master/program/German%20(Germany))? There are about five strings overall.

**Comment by versat** [comment]
Done. I have updated all translation files for German (see other pull requests).

**Comment by RaMMicHaeL** [comment]
Thank you @versat. If you don't mind, can you please take a look at this pull request and check whether it contains meaningful fixes? The pull request: https://github.com/unchecky/unchecky-translate/pull/165

**Comment by versat** [comment]
I don't know how to edit this PR, it always destroys the file.
I've created PR #233 which also contains fixes from @supp0rter (PR #165).
Please use the new PR #233. This PR can be deleted/closed then.
Thanks.

**Pull request closed without merging**
