### PR TITLE
Updated German program strings

### PR DESCRIPTION
**Pull request by RaMMicHaeL**

### CODE REVIEW

**Comment by RaMMicHaeL** [comment]
@LeChuck87 or @FelixKiunke, can you please review the changes? Thanks.

**Comment by FelixKiunke** [comment]
Yep, looks great

**Comment by RaMMicHaeL** [comment]
Thanks!

**Comment by supp0rter** [comment]
Hey!
I'm the one who fixed some german strings in Unchecky. :)
I found some mistake in my translation:

Bad translation:
IDS_MAINCTRL_STATS_NONE "Es wurden bisher keine Häkchen entfernt. Anscheinend bleiben Sie von Programmen mit potentiell ungewollter Software fern, gute Arbeit!"

Fixed translation:
IDS_MAINCTRL_STATS_NONE "Es wurden bisher keine Häkchen entfernt. Anscheinend bleiben Sie Programmen mit potentiell ungewollter Software fern, gute Arbeit!"

also the following translations a bit buggy:
IDS_SHARE_TWITTER_AND   " und "
IDS_SHARE_TWITTER_WARNED "und warnte mich vor %u Angeboten."

should be:
IDS_SHARE_TWITTER_AND   " und "
IDS_SHARE_TWITTER_WARNED "warnte mich vor %u Angeboten."

and this is not translated:
IDS_LOG_CLEAR_TEXT      "&Clear activity log"
IDS_LOG_CLEAR_WARNING   "Activity log will be cleared. Are you sure you want to proceed?"

should be:
IDS_LOG_CLEAR_TEXT      "Aktivitätsprotokoll zurücksetzen"
IDS_LOG_CLEAR_WARNING   "Aktivitätsprotokoll wird zurückgesetzt. Sind Sie sicher, dass Sie fortfahren möchten?"

Greetings
supp0rter

**Comment by FelixKiunke** [comment]
Aren't both versions correct in the first one? :)


Am 17. Oktober 2015 18:51:45 schrieb supp0rter <notifications@github.com>:

**Comment by supp0rter** [comment]
No, thats why I wrote this. :)

**Comment by FelixKiunke** [comment]
Well, if you say so :D

**Comment by RaMMicHaeL** [comment]
Thanks @supp0rter. Could you please edit the file and create a pull request?
https://github.com/unchecky/unchecky-translate/blob/master/program/German%20%28Germany%29/app.txt
Just click on the Edit button in the upper right corner of the text box.

If not, I'll do that later.

**Comment by supp0rter** [comment]
OK RaMMicHael. :)

**Comment by RaMMicHaeL** [comment]
Thanks.

> Also, when the new translation will be integrated into the program (in v0.4 still old translation available). No offense - just asking. ;)

It will be available in the next version of Unchecky.

**Comment by supp0rter** [comment]
RaMMicHaeL, could you delete every file except https://github.com/supp0rter/unchecky-translate/commit/16aa1b9f6806865b339f631bd8f147b9101b4542?

I messed a bit around, dunno how to delete old edited translations of mine...

Thanks.

**Pull request merged**
