### PR TITLE
Update app.txt

### PR DESCRIPTION
**Pull request by Gilson-Olive**
A frase estava incorente, agora possui sentido. 
Espero ter ajudado!

<h1> :D </h1>

### CODE REVIEW

**Comment by Gilson-Olive** [comment]
Works!!
Thnaks!

**Comment by RaMMicHaeL** [comment]
Great, thanks!
@maisonmdsgreen, can you please review the change?

**Comment by RaMMicHaeL** [comment]
The translation will be available in the next version. Thanks again!

**Comment by Gilson-Olive** [comment]
Thank you brother! This software is saving the world

**Pull request merged**
